//! Stopwords

/// Lucene English stopwords.
pub const ENGLISH_LUCENE: &[&str] = &[
    "a", "an", "and", "are", "as", "at", "be", "but", "by", "for", "if", "in", "into", "is", "it",
    "no", "not", "of", "on", "or", "such", "that", "the", "their", "then", "there", "these",
    "they", "this", "to", "was", "will", "with",
];

/// Lucene CJK stopwords.
pub const CJK_LUCENE: &[&str] = &[
    "a", "an", "and", "are", "as", "at", "be", "but", "by", "for", "if", "in", "into", "is", "it",
    "no", "not", "of", "on", "or", "such", "t", "that", "the", "their", "then", "there", "these",
    "they", "this", "to", "was", "will", "with", "www",
];

/// NLTK English stopwords.
pub const ENGLISH_NLTK: &[&str] = &[
    "a",
    "about",
    "above",
    "after",
    "again",
    "against",
    "ain",
    "all",
    "am",
    "an",
    "and",
    "any",
    "are",
    "aren",
    "aren't",
    "as",
    "at",
    "be",
    "because",
    "been",
    "before",
    "being",
    "below",
    "between",
    "both",
    "but",
    "by",
    "can",
    "couldn",
    "couldn't",
    "d",
    "did",
    "didn",
    "didn't",
    "do",
    "does",
    "doesn",
    "doesn't",
    "doing",
    "don",
    "don't",
    "down",
    "during",
    "each",
    "few",
    "for",
    "from",
    "further",
    "had",
    "hadn",
    "hadn't",
    "has",
    "hasn",
    "hasn't",
    "have",
    "haven",
    "haven't",
    "having",
    "he",
    "her",
    "here",
    "hers",
    "herself",
    "him",
    "himself",
    "his",
    "how",
    "i",
    "if",
    "in",
    "into",
    "is",
    "isn",
    "isn't",
    "it",
    "it's",
    "its",
    "itself",
    "just",
    "ll",
    "m",
    "ma",
    "me",
    "mightn",
    "mightn't",
    "more",
    "most",
    "mustn",
    "mustn't",
    "my",
    "myself",
    "needn",
    "needn't",
    "no",
    "nor",
    "not",
    "now",
    "o",
    "of",
    "off",
    "on",
    "once",
    "only",
    "or",
    "other",
    "our",
    "ours",
    "ourselves",
    "out",
    "over",
    "own",
    "re",
    "s",
    "same",
    "shan",
    "shan't",
    "she",
    "she's",
    "should",
    "should've",
    "shouldn",
    "shouldn't",
    "so",
    "some",
    "such",
    "t",
    "than",
    "that",
    "that'll",
    "the",
    "their",
    "theirs",
    "them",
    "themselves",
    "then",
    "there",
    "these",
    "they",
    "this",
    "those",
    "through",
    "to",
    "too",
    "under",
    "until",
    "up",
    "ve",
    "very",
    "was",
    "wasn",
    "wasn't",
    "we",
    "were",
    "weren",
    "weren't",
    "what",
    "when",
    "where",
    "which",
    "while",
    "who",
    "whom",
    "why",
    "will",
    "with",
    "won",
    "won't",
    "wouldn",
    "wouldn't",
    "y",
    "you",
    "you'd",
    "you'll",
    "you're",
    "you've",
    "your",
    "yours",
    "yourself",
    "yourselves",
];

/// NLTK Chinese single stopwords.
pub const CHINESE_NLTK_SINGLE: &[&str] = &[
    "一", "与", "且", "个", "临", "为", "乃", "么", "之", "乎", "乘", "也", "了", "于", "从", "他",
    "以", "们", "任", "但", "何", "你", "依", "俺", "倘", "像", "兮", "其", "冒", "冲", "几", "凭",
    "则", "别", "到", "即", "又", "及", "另", "叫", "可", "各", "同", "向", "吓", "吗", "吧", "吱",
    "呀", "呃", "呕", "呗", "呜", "呢", "呵", "呸", "咋", "和", "咚", "咦", "咱", "咳", "哇", "哈",
    "哉", "哎", "哗", "哟", "哦", "哩", "哪", "哼", "唉", "啊", "啐", "啥", "啦", "喂", "喏", "嗬",
    "嗯", "嗳", "嘎", "嘘", "嘛", "嘻", "嘿", "因", "在", "地", "多", "她", "如", "宁", "它", "对",
    "将", "就", "尽", "己", "并", "归", "当", "彼", "往", "待", "得", "怎", "您", "我", "或", "所",
    "打", "把", "拿", "按", "据", "故", "既", "是", "替", "有", "望", "朝", "本", "来", "某", "此",
    "每", "比", "沿", "焉", "照", "用", "由", "的", "着", "矣", "离", "第", "等", "管", "纵", "经",
    "给", "者", "而", "能", "腾", "自", "至", "若", "虽", "被", "要", "让", "论", "该", "谁", "赶",
    "起", "趁", "跟", "较", "边", "过", "这", "连", "那", "阿", "除", "随", "靠", "顺",
];
